# Generated by Django 5.2.17 on 2026-08-30 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Unique Student Admission / Registration Number.', max_length=30, unique=True)),
                ('roll_number', models.CharField(blank=True, help_text='Class roll number / seat identifier.', max_length=30)),
                ('parent_name', models.CharField(blank=True, help_text='Parent / Guardian full name.', max_length=100)),
                ('parent_phone', models.CharField(blank=True, help_text='Parent / Guardian contact number.', max_length=20)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact phone number.', max_length=20)),
                ('blood_group', models.CharField(blank=True, help_text='e.g., A+, O-, B+, AB+', max_length=5)),
                ('classroom', models.ForeignKey(blank=True, help_text='Assigned class or grade level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['admission_number'],
            },
        ),
    ]
