# Generated by Django 5.2.17 on 2026-08-30 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique Faculty / Employee Identification Number.', max_length=30, unique=True)),
                ('designation', models.CharField(default='Lecturer', help_text='e.g., Professor, Assistant Professor, Lecturer', max_length=100)),
                ('qualification', models.CharField(blank=True, help_text='e.g., Ph.D. in Computer Science, M.Sc. Mathematics', max_length=150)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('bio', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='courses.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['employee_id'],
            },
        ),
    ]
