# Generated by Django 5.2.17 on 2026-08-30 18:36

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(help_text='Assessment title (e.g., Midterm Exam 2026, Quiz 1)', max_length=100)),
                ('exam_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('MIDTERM', 'Midterm Exam'), ('FINAL', 'Final Exam'), ('PROJECT', 'Project / Practical')], default='FINAL', max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks earned by student.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum possible marks.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated automatically on save.', max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='Calculated letter grade (A+, A, B, etc.).', max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='Grade point on a 4.00 scale.', max_digits=3, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['-date_recorded', 'student'],
            },
        ),
    ]
